from .models import ConsumerDispute, EvidenceArtifact


DISPUTES = [
    ConsumerDispute(
        id="case_sub_001",
        merchant_name="Streamly Pro",
        amount=1299,
        currency="USD",
        charge_date="2026-05-12",
        issuer_name="Chase",
        category="canceled_subscription",
        status="draft",
        user_summary="I canceled my trial but was charged for a monthly subscription.",
        created_at="2026-05-20T12:00:00Z",
    ),
    ConsumerDispute(
        id="case_delivery_002",
        merchant_name="Northstar Gear",
        amount=8499,
        currency="USD",
        charge_date="2026-05-06",
        issuer_name="Capital One",
        category="not_received",
        status="needs_evidence",
        user_summary="I ordered a jacket and the merchant has not delivered it or responded.",
        created_at="2026-05-20T12:05:00Z",
    ),
    ConsumerDispute(
        id="case_refund_003",
        merchant_name="FitClass Online",
        amount=5900,
        currency="USD",
        charge_date="2026-04-29",
        issuer_name="Bank of America",
        category="refund_not_received",
        status="draft",
        user_summary="The merchant promised a refund after I canceled, but it has not appeared.",
        created_at="2026-05-20T12:10:00Z",
    ),
]


EVIDENCE = [
    EvidenceArtifact(
        id="ev_sub_statement",
        dispute_id="case_sub_001",
        type="statement_transaction",
        title="Card statement charge",
        source="Chase card statement",
        occurred_at="2026-05-12",
        summary="Streamly Pro charged $12.99 on May 12, 2026.",
    ),
    EvidenceArtifact(
        id="ev_sub_cancel",
        dispute_id="case_sub_001",
        type="cancellation_confirmation",
        title="Cancellation confirmation email",
        source="Email inbox",
        occurred_at="2026-05-10",
        summary="Streamly Pro sent a cancellation confirmation two days before the charge.",
    ),
    EvidenceArtifact(
        id="ev_sub_support",
        dispute_id="case_sub_001",
        type="merchant_message",
        title="Merchant support response",
        source="Support chat",
        occurred_at="2026-05-14",
        summary="Support said the charge would stand because the account remained active, but did not address the cancellation confirmation.",
    ),
    EvidenceArtifact(
        id="ev_delivery_statement",
        dispute_id="case_delivery_002",
        type="statement_transaction",
        title="Card statement charge",
        source="Capital One card statement",
        occurred_at="2026-05-06",
        summary="Northstar Gear charged $84.99 on May 6, 2026.",
    ),
    EvidenceArtifact(
        id="ev_delivery_order",
        dispute_id="case_delivery_002",
        type="order_confirmation",
        title="Order confirmation",
        source="Email receipt",
        occurred_at="2026-05-06",
        summary="Order #NG-4182 was confirmed with estimated delivery by May 13, 2026.",
    ),
    EvidenceArtifact(
        id="ev_refund_statement",
        dispute_id="case_refund_003",
        type="statement_transaction",
        title="Card statement charge",
        source="Bank of America card statement",
        occurred_at="2026-04-29",
        summary="FitClass Online charged $59.00 on April 29, 2026.",
    ),
    EvidenceArtifact(
        id="ev_refund_promise",
        dispute_id="case_refund_003",
        type="refund_promise",
        title="Refund approval email",
        source="Email inbox",
        occurred_at="2026-05-02",
        summary="FitClass Online confirmed a refund would be processed within five business days.",
    ),
]

